services:

  products-db:
    image: widgetario/db
    networks:
      - app-net

  products-api:
    image: widgetario/products-api
    networks:
      - app-net

  stock-api:
    image: widgetario/stock-api
    networks:
      - app-net
  
  web:
    image: widgetario/web
    ports:
      - "8080:80"
    networks:
      - app-net

networks:
  app-net: